version: '3'
services:
  webserver:
    image: nginx
    container_name: nginx_delegate
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: php_delegate
    build:
      context: php
    volumes:
      - ../:/var/www/html/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=development